added fix for precommit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,18 +1,26 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# get all changed files
+# Get all changed files
 ALL_ALTERED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
-echo "Changed files \n: $ALL_ALTERED_FILES"
+echo "Changed files:\n$ALL_ALTERED_FILES"
 
-## list files that needed to be formated
-echo "FILES THAT NEED FORMATTING: "
-npx prettier --list-different $ALL_ALTERED_FILES
+# Format all files and stage the changes
+echo "Formatting files..."
+npx prettier --write $ALL_ALTERED_FILES
 
-## not commiting!
+# Stage the changes
+echo "Staging changes..."
+git add $ALL_ALTERED_FILES
+
+# Check for formatting errors
+echo "Checking for formatting errors..."
 stderrOutput=$(npx prettier --check $ALL_ALTERED_FILES 2>&1)
-echo $?
-	if [[ $? -ne 0 ]]; then
-        echo "File not formatted: $ALL_ALTERED_FILES"
-		exit 1
-	fi
+if [[ $? -ne 0 ]]; then
+    echo "Formatting errors found!"
+    echo "$stderrOutput"
+    exit 1
+else
+    echo "No formatting errors found. Committing..."
+    exit 0
+fi
